"use client";

import React, { useEffect, useState } from 'react';
import { Download, Copy, Check } from 'lucide-react';
import { useRouter } from 'next/navigation';
import ScheduleTable from './ScheduleTable';
import { Subject } from '@/app/lib/types';

interface SharedScheduleViewProps {
    scheduleData: Subject[];
    id: string; // Share ID
    name?: string;
}

export default function SharedScheduleView({ scheduleData, id, name }: SharedScheduleViewProps) {
    const router = useRouter();
    const [copied, setCopied] = useState(false);

    const handleCopyLink = () => {
        navigator.clipboard.writeText(window.location.href);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleAddToPlanner = () => {
        // We use localStorage to pass data to the main app on redirect
        // The main app (Home) should check for this key on mount
        const importPayload = {
            action: 'IMPORT_SHARED',
            data: scheduleData
        };
        localStorage.setItem('pendingScheduleImport', JSON.stringify(importPayload));
        router.push('/');
    };

    return (
        <div className="min-h-screen bg-slate-50 p-4 lg:p-8 font-sans">
            <div className="max-w-[1200px] mx-auto">

                {/* Header */}
                <div className="flex flex-col md:flex-row items-center justify-between gap-4 mb-8 bg-white p-6 rounded-3xl shadow-sm border border-slate-200">
                    <div>
                        <div className="flex items-center gap-2 mb-1">
                            <span className="bg-indigo-100 text-indigo-600 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider">Shared Schedule</span>
                            <span className="text-slate-400 text-xs">#{id.slice(-6)}</span>
                        </div>
                        <h1 className="text-2xl md:text-3xl font-black text-slate-800">{name || "Untitled Schedule"}</h1>
                    </div>

                    <div className="flex items-center gap-3">
                        <button
                            onClick={handleCopyLink}
                            className="bg-white border border-slate-200 hover:bg-slate-50 text-slate-600 px-4 py-2 rounded-xl text-sm font-bold flex items-center gap-2 transition-all cursor-pointer"
                        >
                            {copied ? <Check size={16} className="text-green-500" /> : <Copy size={16} />}
                            {copied ? "Copied" : "Copy Link"}
                        </button>
                        <button
                            onClick={handleAddToPlanner}
                            className="bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-3 rounded-xl text-sm font-bold flex items-center gap-2 shadow-lg shadow-indigo-200 hover:shadow-xl hover:shadow-indigo-300 transition-all active:scale-95 cursor-pointer"
                        >
                            <Download size={18} />
                            Add to My Planner
                        </button>
                    </div>
                </div>

                {/* The Schedule */}
                <ScheduleTable
                    schedule={scheduleData}
                    id="shared-view"
                    exporting={false} // Use normal view
                />

                <div className="text-center mt-12 text-slate-400 text-sm">
                    Generated by <a href="/" className="font-bold text-indigo-500 hover:underline">UniPlanner</a>
                </div>
            </div>
        </div>
    );
}
